In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("HousePricePrediction.csv")

In [39]:
# Drop records with null values
# Drop Id as it doesn't contribute in price
df.drop(['Id'],
             axis=1,
             inplace=True)
df = df.dropna()

df.isnull().sum()
df

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,7917,Inside,1Fam,5,1999,2000,VinylSd,0.0,953.0,175000.0
1456,20,RL,13175,Inside,1Fam,6,1978,1988,Plywood,163.0,1542.0,210000.0
1457,70,RL,9042,Inside,1Fam,9,1941,2006,CemntBd,0.0,1152.0,266500.0
1458,20,RL,9717,Inside,1Fam,6,1950,1996,MetalSd,1029.0,1078.0,142125.0
1459,20,RL,9937,Inside,1Fam,6,1965,1965,HdBoard,290.0,1256.0,147500.0

<!-- s physicalfeatures, location, and condition -->

In [40]:
categories = df["MSZoning"].unique().tolist()
print(categories)

['RL', 'RM', 'C (all)', 'FV', 'RH']

In [41]:
X = df.drop(columns=['LotConfig','Exterior1st',"SalePrice","BsmtFinSF2"])
y = df["SalePrice"]


X['BldgType'] = X['BldgType'].map({'1Fam':1,'2fmCon':2,'Duplex':3,'TwnhsE':4,'Twnhs':5})
X['MSZoning']=X['MSZoning'].map({'RL':1, 'RM':2, 'C (all)':3, 'FV':4, 'RH':5, np.nan:6})

In [42]:
X = X.fillna(X.mean())
y = y.fillna(y.mean())
X

,MSSubClass,MSZoning,LotArea,BldgType,OverallCond,YearBuilt,YearRemodAdd,TotalBsmtSF
0,60,1,8450,1,5,2003,2003,856.0
1,20,1,9600,1,8,1976,1976,1262.0
2,60,1,11250,1,5,2001,2002,920.0
3,70,1,9550,1,5,1915,1970,756.0
4,60,1,14260,1,5,2000,2000,1145.0
...,...,...,...,...,...,...,...,...
1455,60,1,7917,1,5,1999,2000,953.0
1456,20,1,13175,1,6,1978,1988,1542.0
1457,70,1,9042,1,9,1941,2006,1152.0
1458,20,1,9717,1,6,1950,1996,1078.0
1459,20,1,9937,1,6,1965,1965,1256.0

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [44]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [47]:
y_pred = model.predict(X_test)
y_pred

array([191054.53025713, 247491.46749393, 113654.6809373 , 140147.72326505,
       259845.97155841, 133483.26186469, 181097.08861998, 119789.18161915,
       105598.72648842, 144508.26346592, 115498.9303576 , 144164.70007673,
       110088.70854152, 244720.27409114, 213726.7962047 , 178164.12344855,
       214073.22256836, 178927.51272782, 103700.05507208, 238833.75373042,
       175447.15921922, 217775.45540712, 208506.03224676, 167988.41706158,
       229659.59990843, 177709.07275631, 235612.82638462, 119748.8071892 ,
       212009.04483268, 209622.90364012, 113147.38777423, 226613.54942116,
       223546.93463733, 134920.11079658, 258107.01203687, 158764.94890859,
       171428.400521  , 213788.31101384, 246440.83655205,  60519.92275685,
       113050.9110805 , 213154.33104874, 150733.44813159, 292077.08602181,
       137794.37067792,  89913.1498461 , 135405.45654964, 150443.67332121,
       288669.26102816, 140903.43163585, 118913.76222786, 205308.096917  ,
       103901.31318666, 212197.4275956 , 167644.11461679, 263237.28483552,
       190140.54123196, 181835.76906557, 193256.34436492, 105680.38861236,
        76083.42921201, 189178.76270561, 238007.57019818, 252966.35463629,
       268227.84873635, 188671.45836579, 113936.95255915, 262312.56110024,
       185720.18330649, 171688.90704381,  77289.40442367, 144999.89363112,
       128922.92334897,  28071.90314957, 314835.97590139, 261406.41411747,
       245267.9674042 , 233538.17808735, 149340.23035593, 146781.66660789,
       125312.23256765,  87343.01493802, 135498.75851435, 106591.76831697,
       169078.11699892, 160074.12551325, 239752.47689541, 258330.34086211,
       167641.87823723, 211202.79182826, 188148.31301877, 156116.75719411,
       166089.89111527, 236257.6887081 , 191655.7124897 , 232511.16045277,
       167443.06055292, 169292.74881284, 245623.79705653, 188718.35076804,
       193746.64483893, 215634.4004755 , 254075.26061888, 158500.07904063,
       235566.94868591, 157280.5429422 , 194507.57392937, 278794.83578775,
       190549.33890708, 175693.34286531,  50957.68723881, 167405.96399757,
       193530.27547487, 174524.34765095, 225213.03956308, 145129.35052229,
       164691.24854667, 142929.446958  ,  77813.48236746, 367553.68108977,
       150781.34223226, 167644.11461679, 208917.03601238, 155794.37908549,
       211196.73963553, 147324.13173837, 216315.4526277 , 109908.28282822,
       212905.63746244, 170519.84300419, 209022.42799132, 273686.07272574,
       208066.8303513 , 103896.67882771,  74419.29551126, 263768.45408536,
       238840.15492416, 164280.52259372, 250020.85280839, 330372.74709124,
       251152.02861691, 172944.96617434, 177449.88363036, 129356.33021526,
       212405.35344606, 169488.75828193, 167289.81686841, 237756.72985608,
       208584.74833287,  78855.45848711,  84264.86688275, 140218.09335426,
       230812.62427767, 131212.76200001, 101609.38446144, 136216.71283275,
       148846.55514403, 155369.34864995, 119855.24411523, 151264.35821226,
       229481.42721581, 155894.96515594, 258641.15233764, 188446.94582596,
       120734.52095714, 176436.99266277, 215071.48188889, 266673.05729104,
       306358.14393286, 160490.56110934, 273255.83871834, 135824.13181988,
       115707.3861554 , 117642.23194672, 259906.22338462,  78637.26093899,
       107939.00696902, 214824.45056153, 152870.84154732, 149368.28963269,
       231941.82543443,  91289.29338928, 186853.9503613 , 156387.57010232,
       229647.87695719,  98741.9824546 , 247577.64989417, 206902.99042555,
       209184.98510106,  85038.44981351, 127588.24384563, 125283.02592768,
       117415.03273601, 205653.30603601, 177619.59093614, 166438.65964813,
       198873.01653827,  93873.70537715, 164613.23899797,  97322.21608259,
       245086.93132017, 204274.7717671 , 148307.15490928, 251242.27157923,
       228718.78665524, 176854.62816075, 222001.55308399, 154214.02007444,
       164327.61107438, 136323.56040085, 186387.80020186, 137921.00789233,
       131385.62403204, 171688.90704381, 228110.71431406, 255814.59711584,
       200483.1226441 , 179343.6335456 , 162082.55847212,  76435.32940736,
       151891.60153536, 206204.44073465, 202058.36968614, 107788.36681994,
       244825.6174874 , 193095.80167609,  86610.56874874, 135527.7118691 ,
       192698.30862316,  97164.77660264, 100899.72246155, 186608.77058788,
       128015.68397435, 150271.98850193, 201353.02363758, 149178.47551596,
       224388.58814351, 219674.43146561, 217225.38973828, 137054.16201967,
       138424.74261784, 199955.21803247, 225916.92887361, 262886.48388509,
       176010.64182551, 200290.54722029, 177164.46949117, 195323.54532755,
       145884.32907544, 102055.73444397, 217980.63052865, 173004.02759875,
       145922.75391834,  81847.53185416, 154685.54042759, 139992.78413053,
       158562.35464408, 102872.11679453, 188474.49157678, 229664.67324382,
       281412.10260306, 184567.83094692, 159624.88634277, 253255.08508506,
       264162.16508582, 227505.23513881, 186562.5034368 , 166879.02196367,
       129888.62480344, 184186.03379982, 291450.23616863, 185916.63142499,
       236644.13815976, 110532.28213029,  52447.72341412, 156577.92126233,
       170257.10508179, 248732.51943049, 234884.05487825, 131332.13447891,
       222202.84566958, 109685.20685865, 214098.88638413, 148037.18293609,
       264362.38982574, 193630.51586052, 220019.14546912, 157151.00951663,
       251716.97796391, 207452.86702385, 120319.48175833, 150426.21032339,
       158475.22041207, 202938.1654627 ,  88784.4620232 , 113556.25096128,
       119136.45860987, 157037.70859729, 207009.6171546 , 157480.24381972,
       207148.65762127, 247188.21657289, 164674.41909641, 181200.84407996,
       186832.38392701, 175936.49127525, 163059.64953042, 223175.60884498,
       193257.64081621, 157463.71109486, 164498.46982573, 224355.61969053,
        99097.55034351, 155944.59103229, 124963.53905127, 214629.61649452,
       218188.9886862 , 176779.82967886, 255462.38527815,  27309.046876  ,
       251081.72786529, 199463.80925354, 128718.95406755,  98436.58371746,
       223446.82857134, 192575.02942366, 192390.77827468, 231383.49744824,
       160099.95136631, 142571.5609403 , 156527.83563957, 158008.30343493,
       194964.55534448, 205421.8348715 , 181730.04156527, 141042.48654051,
       125674.04133553, 184111.91165235,  85053.21489048, 246950.03747277,
       195559.04013613, 165182.26221428, 183892.90173935, 215283.17128069,
       224420.14211844, 237436.53909258, 265271.04335219, 153402.88545953,
       196629.4442951 , 196978.96896935, 184792.97533463, 317106.61248253,
       222452.89289398, 199391.25320466, 264201.88239185, 180534.08986331,
       167778.49224718, 111405.31617608, 207332.71447874, 278233.91286648,
       177495.00721026, 142006.68149117, 244141.9415889 , 228500.84417072,
       151794.51979349, 204767.166652  , 187283.49139547,  95217.94789726,
       152067.04901105, 170406.0368803 , 159140.61402855, 215885.97625121,
       112396.90796593, 204974.38187008, 175207.48957027, 166341.04239555,
       147324.21374389, 231346.13345436,  81787.56201761, 237537.84690653,
       179106.22090297, 241492.30001065, 202413.63892467, 196674.53037306,
       133296.87094844, 193839.12022621, 174957.32077874, 109945.44855723,
       273101.20592859, 173251.66880308, 116800.94401316, 106358.1556561 ,
       139724.07879232, 272864.82483866, 163077.79735728, 270064.92455558,
       115723.86465639, 166717.8113558 , 208128.44530439, 115947.12617123,
       207326.13884879, 302193.62492116, 118400.57029747, 157648.15650389,
       184863.65835415, 145011.7127824 , 216829.44244284, 186362.58764928,
       245872.11040664, 181912.49660651, 189932.87210075, 241011.92096279,
        81666.24980517, 259411.01916544, 159597.56750231, 295982.28973235,
       154669.89129283, 241960.13018931, 239205.63778701, 148864.46571721,
       213468.31611731, 204461.02320405, 181958.71511741, 153903.52253877,
       216367.77110744, 179262.12705073, 214360.43846142, 185838.71829467,
       224005.79308517, 221458.46232769, 133846.88102594, 169681.88105774,
       232048.74296183, 169025.35308372, 192861.57869662, 223208.32974576,
       146500.06338477, 304405.89972877, 179842.9265463 , 176977.07950728,
       218216.63647437, 277317.80027827, 204593.99121071, 191109.34962454,
       212956.07388932, 161243.9202262 , 193326.43635652, 231176.01927984,
       143178.8579051 , 168306.17846969, 129206.04890155, 122970.60947918,
       125344.79840768, 182341.96862618, 137667.97800595, 229208.15448269,
       240080.65183179, 253602.68414887, 232832.68056827, 112646.20539666,
       133648.05751288, 100115.9302461 , 202806.09127293, 242044.46799646,
       198426.64743724, 320424.4023076 , 176091.50078814, 204767.166652  ,
       144999.94576036, 271430.33672265, 157859.2293487 ,  54997.67958962,
       158245.76068224, 130293.14397319, 214165.55592662, 282258.70238802,
       205464.95293587, 122871.81687112, 100101.01205905, 199633.36134548,
       154728.16770715, 139858.73404955])

In [35]:
y_test

2437    180921.19589
2470    180921.19589
2359    180921.19589
789     187500.00000
1642    180921.19589
            ...
1018    160000.00000
1475    180921.19589
192     192000.00000
801     109900.00000
174     184000.00000
Name: SalePrice, Length: 964, dtype: float64

In [48]:
# evaluate the model

from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"these is the evaluation value--{r2}" )

these is the evaluation value--0.5960992797684123

In [38]:
n = X_test.shape[0]
p = X_test.shape[1]

adjusted_r2 = 1-((1-r2)*(n-1)/(n-p-1))

print(f"adjusted r2 {adjusted_r2}")

adjusted r2 0.3013477150365169