In [41]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score,accuracy_score,recall_score
from sklearn.preprocessing import StandardScaler

In [27]:
df = pd.read_csv('Iris.csv')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [29]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### feature eng

In [30]:
df['Sepal_LW_Ratio'] = round(df['SepalLengthCm']/df['SepalWidthCm'], 3)
df['Petal_LW_Ratio'] = round(df['PetalLengthCm']/df['PetalWidthCm'], 3)
df['Sepal_Petal_Ratio'] = round(df['SepalLengthCm']/df['PetalLengthCm'], 3)

In [31]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Sepal_LW_Ratio,Petal_LW_Ratio,Sepal_Petal_Ratio
0,1,5.1,3.5,1.4,0.2,Iris-setosa,1.457,7.000,3.643
1,2,4.9,3.0,1.4,0.2,Iris-setosa,1.633,7.000,3.500
2,3,4.7,3.2,1.3,0.2,Iris-setosa,1.469,6.500,3.615
3,4,4.6,3.1,1.5,0.2,Iris-setosa,1.484,7.500,3.067
4,5,5.0,3.6,1.4,0.2,Iris-setosa,1.389,7.000,3.571
...,...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,2.233,2.261,1.288
146,147,6.3,2.5,5.0,1.9,Iris-virginica,2.520,2.632,1.260
147,148,6.5,3.0,5.2,2.0,Iris-virginica,2.167,2.600,1.250
148,149,6.2,3.4,5.4,2.3,Iris-virginica,1.824,2.348,1.148
149,150,5.9,3.0,5.1,1.8,Iris-virginica,1.967,2.833,1.157

Logistic Regression

In [34]:
X = df.drop(['Id','Species'],axis=1)
y = df['Species']

In [35]:
X_train , X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.20,random_state=42
)

In [38]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(max_iter=3000)

In [39]:
logistic_model.fit(X_train,y_train)

LogisticRegression(max_iter=3000)

precision_score in scikit-learn defaults to binary classification (one positive, one negative class). Since `y_test` and `y_pred` contain three classes (multiclass classification), precision must be aggregated across classes (e.g., with `average='weighted'`, `micro`, or `macro`). Without specifying an averaging strategy, sklearn cannot combine per-class precision values, so it raises an error.

In [40]:
y_pred = logistic_model.predict(X_test)

In [46]:
print("accuracy :-" , accuracy_score(y_test,y_pred) *100,"%")
print("precision :-" , precision_score(y_test,y_pred,average='weighted') *100,"%")

accuracy :- 100.0 %
precision :- 100.0 %

### navie_bayes

In [47]:
from sklearn.naive_bayes import GaussianNB

In [48]:
GaussianNB_model = GaussianNB()
GaussianNB_model.fit(X_train,y_train)
y_pred = GaussianNB_model.predict(X_test)

In [49]:
print("accuracy :-" , accuracy_score(y_test,y_pred) *100,"%")
print("precision :-" , precision_score(y_test,y_pred,average='weighted') *100,"%")

accuracy :- 100.0 %
precision :- 100.0 %

### KNN classifier with pipe

In [50]:
from sklearn.pipeline import Pipeline

In [51]:
from sklearn.neighbors import KNeighborsClassifier
kNN_model = KNeighborsClassifier()

In [52]:
classifier = [('scaler', StandardScaler()), ('kNN', KNeighborsClassifier())]

pipe   = Pipeline(classifier)

In [54]:
kNN_model.fit(X_train,y_train)
Y_pred = kNN_model.predict(X_test)
print("accuracy :-" , accuracy_score(y_test,Y_pred) *100,"%")
print("precision :-" , precision_score(y_test,Y_pred,average='weighted') *100,"%")

accuracy :- 100.0 %
precision :- 100.0 %

In [57]:
lst = [x for x in range(1,100,2)]
print(lst)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]

In [58]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors' :[x for x in range(1,100,2)]}

classifierCV = GridSearchCV(
    kNN_model,
    param_grid,
    cv = 5 
)

In [59]:
classifierCV.fit(X_train,y_train)

c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 492, in __call__
    return estimator.score(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 446, in score
    return super().score(X, y, sample_weight)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\base.py", line 548, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ~~~~~~~~~~~~^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 274, in predict
    neigh_ind = self.kneighbors(X, return_distance=False)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_base.py", line 854, in kneighbors
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 97, n_samples_fit = 96, n_samples = 24

  warnings.warn(
c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 492, in __call__
    return estimator.score(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 446, in score
    return super().score(X, y, sample_weight)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\base.py", line 548, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ~~~~~~~~~~~~^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 274, in predict
    neigh_ind = self.kneighbors(X, return_distance=False)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_base.py", line 854, in kneighbors
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 97, n_samples_fit = 96, n_samples = 24

  warnings.warn(
c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 492, in __call__
    return estimator.score(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 446, in score
    return super().score(X, y, sample_weight)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\base.py", line 548, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ~~~~~~~~~~~~^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 274, in predict
    neigh_ind = self.kneighbors(X, return_distance=False)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_base.py", line 854, in kneighbors
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 97, n_samples_fit = 96, n_samples = 24

  warnings.warn(
c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 492, in __call__
    return estimator.score(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 446, in score
    return super().score(X, y, sample_weight)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\base.py", line 548, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ~~~~~~~~~~~~^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 274, in predict
    neigh_ind = self.kneighbors(X, return_distance=False)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_base.py", line 854, in kneighbors
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 97, n_samples_fit = 96, n_samples = 24

  warnings.warn(
c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 492, in __call__
    return estimator.score(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 446, in score
    return super().score(X, y, sample_weight)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\base.py", line 548, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ~~~~~~~~~~~~^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 274, in predict
    neigh_ind = self.kneighbors(X, return_distance=False)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_base.py", line 854, in kneighbors
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 97, n_samples_fit = 96, n_samples = 24

  warnings.warn(
c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 492, in __call__
    return estimator.score(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 446, in score
    return super().score(X, y, sample_weight)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\base.py", line 548, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ~~~~~~~~~~~~^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 274, in predict
    neigh_ind = self.kneighbors(X, return_distance=False)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_base.py", line 854, in kneighbors
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 99, n_samples_fit = 96, n_samples = 24

  warnings.warn(
c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 492, in __call__
    return estimator.score(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 446, in score
    return super().score(X, y, sample_weight)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\base.py", line 548, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ~~~~~~~~~~~~^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 274, in predict
    neigh_ind = self.kneighbors(X, return_distance=False)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_base.py", line 854, in kneighbors
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 99, n_samples_fit = 96, n_samples = 24

  warnings.warn(
c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 492, in __call__
    return estimator.score(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 446, in score
    return super().score(X, y, sample_weight)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\base.py", line 548, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ~~~~~~~~~~~~^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 274, in predict
    neigh_ind = self.kneighbors(X, return_distance=False)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_base.py", line 854, in kneighbors
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 99, n_samples_fit = 96, n_samples = 24

  warnings.warn(
c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 492, in __call__
    return estimator.score(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 446, in score
    return super().score(X, y, sample_weight)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\base.py", line 548, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ~~~~~~~~~~~~^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 274, in predict
    neigh_ind = self.kneighbors(X, return_distance=False)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_base.py", line 854, in kneighbors
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 99, n_samples_fit = 96, n_samples = 24

  warnings.warn(
c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 492, in __call__
    return estimator.score(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 446, in score
    return super().score(X, y, sample_weight)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\base.py", line 548, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ~~~~~~~~~~~~^^^
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 274, in predict
    neigh_ind = self.kneighbors(X, return_distance=False)
  File "c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\neighbors\_base.py", line 854, in kneighbors
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 99, n_samples_fit = 96, n_samples = 24

  warnings.warn(
c:\Users\gk480\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [0.94166667 0.96666667 0.96666667 0.95       0.95       0.95
 0.95       0.95       0.95       0.94166667 0.93333333 0.925
 0.925      0.925      0.91666667 0.9        0.9        0.89166667
 0.89166667 0.88333333 0.875      0.875      0.86666667 0.86666667
 0.85833333 0.85833333 0.85833333 0.85833333 0.83333333 0.79166667
 0.68333333 0.475      0.39166667 0.38333333 0.36666667 0.35833333
 0.35       0.35833333 0.35833333 0.35833333 0.35833333 0.35833333
 0.35833333 0.35833333 0.35833333 0.35833333 0.36666667 0.36666667
        nan        nan]
  warnings.warn(

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21,
                                         23, 25, 27, 29, 31, 33, 35, 37, 39, 41,
                                         43, 45, 47, 49, 51, 53, 55, 57, 59, ...]})

In [62]:
y_pred = classifierCV.predict(X_test)
print('recall',recall_score(y_test,y_pred,average='weighted'))
print('accuracy_score' ,accuracy_score(y_test,y_pred) *100,"%")
print('precision_score',precision_score(y_test,y_pred,average='weighted') *100,"%")
res = pd.DataFrame(classifierCV.cv_results_)
print(classifierCV.best_params_)

recall 1.0
accuracy_score 100.0 %
precision_score 100.0 %
{'n_neighbors': 3}